# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-08 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='select_order',
        ),
    ]
