# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chef', '0003_auto_20200120_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='dining',
            new_name='dining_date',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='seat',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='name of event',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
