# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture_food',
            field=models.ImageField(upload_to='static/food/images'),
        ),
    ]
