# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191004_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture_food',
            field=models.ImageField(upload_to='food/images'),
        ),
    ]
