# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.FloatField(blank=True, choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default=None, null=True),
        ),
    ]
